import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full">
        <nav className="flex gap-2.5 p-2 m-2">
          <Link href="/"> <h1>Home</h1> </Link>
          <Link href="/about"> <h1>About</h1> </Link>
          <Link href="/contect"> <h1>Contect</h1></Link>
          <Link href="/user"> <h1>User</h1></Link>
        </nav>
        {children}

      </body>
    </html>
  );
}
